/**
 * Country name → ISO 3166-1 alpha-3 code mapping.
 *
 * Purpose: FARA data identifies foreign principals by country NAME (in DOJ
 * house style, e.g. "KOREA SOUTH", "CHINA PEOPLES REPUBLIC"), while
 * USAspending foreign-aid data keys countries by ISO alpha-3 CODE (e.g.
 * "KOR", "CHN"). The influence-chain views join on country_code, so FARA
 * names must be resolved to the same codes.
 *
 * Lookup is against a normalized form of the name (uppercase, letters and
 * spaces only) so "KOREA, SOUTH", "Korea South" and "KOREA SOUTH" all match.
 * Unknown names resolve to null — callers should leave country_code NULL
 * rather than guess.
 */

function normalize(name) {
  return String(name || '')
    .toUpperCase()
    .replace(/['’.]/g, '')   // strip apostrophes/periods: PEOPLE'S -> PEOPLES
    .replace(/[^A-Z ]+/g, ' ')    // any other punctuation becomes a space
    .replace(/\s+/g, ' ')
    .trim();
}

// Canonical names plus DOJ/FARA-style and common variants, keyed by
// normalized form.
const NAME_TO_ISO3 = {
  'AFGHANISTAN': 'AFG',
  'ALBANIA': 'ALB',
  'ALGERIA': 'DZA',
  'ANDORRA': 'AND',
  'ANGOLA': 'AGO',
  'ANTIGUA AND BARBUDA': 'ATG',
  'ANTIGUA BARBUDA': 'ATG',
  'ARGENTINA': 'ARG',
  'ARMENIA': 'ARM',
  'AUSTRALIA': 'AUS',
  'AUSTRIA': 'AUT',
  'AZERBAIJAN': 'AZE',
  'BAHAMAS': 'BHS',
  'THE BAHAMAS': 'BHS',
  'BAHRAIN': 'BHR',
  'BANGLADESH': 'BGD',
  'BARBADOS': 'BRB',
  'BELARUS': 'BLR',
  'BELGIUM': 'BEL',
  'BELIZE': 'BLZ',
  'BENIN': 'BEN',
  'BHUTAN': 'BTN',
  'BOLIVIA': 'BOL',
  'BOSNIA AND HERZEGOVINA': 'BIH',
  'BOSNIA HERZEGOVINA': 'BIH',
  'BOSNIA': 'BIH',
  'BOTSWANA': 'BWA',
  'BRAZIL': 'BRA',
  'BRUNEI': 'BRN',
  'BRUNEI DARUSSALAM': 'BRN',
  'BULGARIA': 'BGR',
  'BURKINA FASO': 'BFA',
  'BURMA': 'MMR',
  'MYANMAR': 'MMR',
  'MYANMAR BURMA': 'MMR',
  'BURUNDI': 'BDI',
  'CABO VERDE': 'CPV',
  'CAPE VERDE': 'CPV',
  'CAMBODIA': 'KHM',
  'CAMEROON': 'CMR',
  'CANADA': 'CAN',
  'CENTRAL AFRICAN REPUBLIC': 'CAF',
  'CHAD': 'TCD',
  'CHILE': 'CHL',
  'CHINA': 'CHN',
  'CHINA PEOPLES REPUBLIC': 'CHN',
  'PEOPLES REPUBLIC OF CHINA': 'CHN',
  'CHINA PEOPLES REPUBLIC OF': 'CHN',
  'COLOMBIA': 'COL',
  'COMOROS': 'COM',
  'CONGO': 'COG',
  'CONGO REPUBLIC': 'COG',
  'REPUBLIC OF THE CONGO': 'COG',
  'CONGO BRAZZAVILLE': 'COG',
  'CONGO DEMOCRATIC REPUBLIC': 'COD',
  'CONGO DEMOCRATIC REPUBLIC OF THE': 'COD',
  'CONGO REPUBLIC OF THE': 'COG',
  'DEMOCRATIC REPUBLIC OF THE CONGO': 'COD',
  'DEMOCRATIC REPUBLIC OF CONGO': 'COD',
  'CONGO KINSHASA': 'COD',
  'DR CONGO': 'COD',
  'ZAIRE': 'COD',
  'COSTA RICA': 'CRI',
  'COTE D IVOIRE': 'CIV',
  'COTE DIVOIRE': 'CIV',
  'IVORY COAST': 'CIV',
  'COTE DIVOIRE IVORY COAST': 'CIV',
  'CROATIA': 'HRV',
  'CUBA': 'CUB',
  'CYPRUS': 'CYP',
  'CZECH REPUBLIC': 'CZE',
  'CZECHIA': 'CZE',
  'CZECHOSLOVAKIA': 'CZE',
  'DENMARK': 'DNK',
  'DJIBOUTI': 'DJI',
  'DOMINICA': 'DMA',
  'DOMINICAN REPUBLIC': 'DOM',
  'ECUADOR': 'ECU',
  'EGYPT': 'EGY',
  'EL SALVADOR': 'SLV',
  'EQUATORIAL GUINEA': 'GNQ',
  'ERITREA': 'ERI',
  'ESTONIA': 'EST',
  'ESWATINI': 'SWZ',
  'SWAZILAND': 'SWZ',
  'ETHIOPIA': 'ETH',
  'FIJI': 'FJI',
  'FINLAND': 'FIN',
  'FRANCE': 'FRA',
  'GABON': 'GAB',
  'GAMBIA': 'GMB',
  'THE GAMBIA': 'GMB',
  'GEORGIA': 'GEO',
  'GEORGIA REPUBLIC': 'GEO',
  'REPUBLIC OF GEORGIA': 'GEO',
  'GERMANY': 'DEU',
  'GERMANY FEDERAL REPUBLIC': 'DEU',
  'WEST GERMANY': 'DEU',
  'GHANA': 'GHA',
  'GREECE': 'GRC',
  'GRENADA': 'GRD',
  'GUATEMALA': 'GTM',
  'GUINEA': 'GIN',
  'GUINEA BISSAU': 'GNB',
  'GUYANA': 'GUY',
  'HAITI': 'HTI',
  'HONDURAS': 'HND',
  'HONG KONG': 'HKG',
  'HUNGARY': 'HUN',
  'ICELAND': 'ISL',
  'INDIA': 'IND',
  'INDONESIA': 'IDN',
  'IRAN': 'IRN',
  'IRAQ': 'IRQ',
  'IRELAND': 'IRL',
  'ISRAEL': 'ISR',
  'ITALY': 'ITA',
  'JAMAICA': 'JAM',
  'JAPAN': 'JPN',
  'JORDAN': 'JOR',
  'KAZAKHSTAN': 'KAZ',
  'KENYA': 'KEN',
  'KIRIBATI': 'KIR',
  'KOREA NORTH': 'PRK',
  'NORTH KOREA': 'PRK',
  'KOREA DEMOCRATIC PEOPLES REPUBLIC': 'PRK',
  'KOREA SOUTH': 'KOR',
  'SOUTH KOREA': 'KOR',
  'KOREA': 'KOR',
  'KOREA REPUBLIC': 'KOR',
  'KOREA REPUBLIC OF': 'KOR',
  'REPUBLIC OF KOREA': 'KOR',
  'KOSOVO': 'XKX',
  'KUWAIT': 'KWT',
  'KYRGYZSTAN': 'KGZ',
  'LAOS': 'LAO',
  'LATVIA': 'LVA',
  'LEBANON': 'LBN',
  'LESOTHO': 'LSO',
  'LIBERIA': 'LBR',
  'LIBYA': 'LBY',
  'LIECHTENSTEIN': 'LIE',
  'LITHUANIA': 'LTU',
  'LUXEMBOURG': 'LUX',
  'MACAU': 'MAC',
  'MACAO': 'MAC',
  'MADAGASCAR': 'MDG',
  'MALAWI': 'MWI',
  'MALAYSIA': 'MYS',
  'MALDIVES': 'MDV',
  'MALI': 'MLI',
  'MALTA': 'MLT',
  'MARSHALL ISLANDS': 'MHL',
  'MAURITANIA': 'MRT',
  'MAURITIUS': 'MUS',
  'MEXICO': 'MEX',
  'MICRONESIA': 'FSM',
  'MOLDOVA': 'MDA',
  'MONACO': 'MCO',
  'MONGOLIA': 'MNG',
  'MONTENEGRO': 'MNE',
  'MOROCCO': 'MAR',
  'MOZAMBIQUE': 'MOZ',
  'NAMIBIA': 'NAM',
  'NAURU': 'NRU',
  'NEPAL': 'NPL',
  'NETHERLANDS': 'NLD',
  'THE NETHERLANDS': 'NLD',
  'HOLLAND': 'NLD',
  'NEW ZEALAND': 'NZL',
  'NICARAGUA': 'NIC',
  'NIGER': 'NER',
  'NIGERIA': 'NGA',
  'NORTH MACEDONIA': 'MKD',
  'MACEDONIA': 'MKD',
  'NORWAY': 'NOR',
  'OMAN': 'OMN',
  'PAKISTAN': 'PAK',
  'PALAU': 'PLW',
  'PALESTINE': 'PSE',
  'PALESTINIAN TERRITORIES': 'PSE',
  'WEST BANK': 'PSE',
  'GAZA': 'PSE',
  'PANAMA': 'PAN',
  'PAPUA NEW GUINEA': 'PNG',
  'PARAGUAY': 'PRY',
  'PERU': 'PER',
  'PHILIPPINES': 'PHL',
  'POLAND': 'POL',
  'PORTUGAL': 'PRT',
  'QATAR': 'QAT',
  'ROMANIA': 'ROU',
  'RUSSIA': 'RUS',
  'RUSSIAN FEDERATION': 'RUS',
  'SOVIET UNION': 'RUS',
  'USSR': 'RUS',
  'RWANDA': 'RWA',
  'SAINT KITTS AND NEVIS': 'KNA',
  'ST KITTS AND NEVIS': 'KNA',
  'SAINT LUCIA': 'LCA',
  'ST LUCIA': 'LCA',
  'SAINT VINCENT AND THE GRENADINES': 'VCT',
  'ST VINCENT AND THE GRENADINES': 'VCT',
  'SAMOA': 'WSM',
  'SAN MARINO': 'SMR',
  'SAO TOME AND PRINCIPE': 'STP',
  'SAUDI ARABIA': 'SAU',
  'SENEGAL': 'SEN',
  'SERBIA': 'SRB',
  'SERBIA AND MONTENEGRO': 'SRB',
  'YUGOSLAVIA': 'SRB',
  'SEYCHELLES': 'SYC',
  'SIERRA LEONE': 'SLE',
  'SINGAPORE': 'SGP',
  'SLOVAKIA': 'SVK',
  'SLOVAK REPUBLIC': 'SVK',
  'SLOVENIA': 'SVN',
  'SOLOMON ISLANDS': 'SLB',
  'SOMALIA': 'SOM',
  'SOUTH AFRICA': 'ZAF',
  'SOUTH SUDAN': 'SSD',
  'SPAIN': 'ESP',
  'SRI LANKA': 'LKA',
  'SUDAN': 'SDN',
  'SURINAME': 'SUR',
  'SWEDEN': 'SWE',
  'SWITZERLAND': 'CHE',
  'SYRIA': 'SYR',
  'TAIWAN': 'TWN',
  'TAIWAN REPUBLIC OF CHINA': 'TWN',
  'REPUBLIC OF CHINA': 'TWN',
  'TAJIKISTAN': 'TJK',
  'TANZANIA': 'TZA',
  'THAILAND': 'THA',
  'TIMOR LESTE': 'TLS',
  'EAST TIMOR': 'TLS',
  'TOGO': 'TGO',
  'TONGA': 'TON',
  'TRINIDAD AND TOBAGO': 'TTO',
  'TRINIDAD TOBAGO': 'TTO',
  'TUNISIA': 'TUN',
  'TURKEY': 'TUR',
  'TURKIYE': 'TUR',
  'TURKMENISTAN': 'TKM',
  'TUVALU': 'TUV',
  'UGANDA': 'UGA',
  'UKRAINE': 'UKR',
  'UNITED ARAB EMIRATES': 'ARE',
  'UAE': 'ARE',
  'UNITED KINGDOM': 'GBR',
  'GREAT BRITAIN': 'GBR',
  'ENGLAND': 'GBR',
  'SCOTLAND': 'GBR',
  'WALES': 'GBR',
  'NORTHERN IRELAND': 'GBR',
  'UK': 'GBR',
  'URUGUAY': 'URY',
  'UZBEKISTAN': 'UZB',
  'VANUATU': 'VUT',
  'VATICAN': 'VAT',
  'VATICAN CITY': 'VAT',
  'VATICAN CITY STATE': 'VAT',
  'HOLY SEE': 'VAT',
  'HOLY SEE VATICAN': 'VAT',
  'HOLY SEE VATICAN CITY': 'VAT',
  'VENEZUELA': 'VEN',
  'VIETNAM': 'VNM',
  'VIET NAM': 'VNM',
  'YEMEN': 'YEM',
  'ZAMBIA': 'ZMB',
  'ZIMBABWE': 'ZWE',
  // Territories and dependencies that appear in FARA data
  'ARUBA': 'ABW',
  'BERMUDA': 'BMU',
  'BRITISH VIRGIN ISLANDS': 'VGB',
  'CAYMAN ISLANDS': 'CYM',
  'FRENCH POLYNESIA': 'PYF',
  'GIBRALTAR': 'GIB',
  'GREENLAND': 'GRL',
  'GUERNSEY': 'GGY',
  'ISLE OF MAN': 'IMN',
  'JERSEY': 'JEY',
  'NEW CALEDONIA': 'NCL',
  'PUERTO RICO': 'PRI',
  'CURACAO': 'CUW',
  'FAROE ISLANDS': 'FRO',
  'TURKS AND CAICOS ISLANDS': 'TCA',
  'ANGUILLA': 'AIA',
  'MONTSERRAT': 'MSR',
  // Partially-recognized states with ISO codes
  'SAHARAWI ARAB DEMOCRATIC REPUBLIC': 'ESH',
  'WESTERN SAHARA': 'ESH',
  // Somaliland has no ISO code of its own; USAspending files its aid under
  // Somalia, so map it there for linkage purposes.
  'SOMALILAND': 'SOM',
  // Deliberately unmapped (no ISO country to link): INTERNATIONAL, TIBET
};

/**
 * Resolve a country name to its ISO 3166-1 alpha-3 code, or null if unknown.
 */
function toIso3(name) {
  return NAME_TO_ISO3[normalize(name)] || null;
}

module.exports = { toIso3, normalize };
