/**
 * All 50 U.S. State Governors as of early 2026.
 * Format: [state, name, party, termEnds]
 */

module.exports = [
  ['AL', 'Kay Ivey', 'Republican', 2027],
  ['AK', 'Mike Dunleavy', 'Republican', 2026],
  ['AZ', 'Katie Hobbs', 'Democrat', 2027],
  ['AR', 'Sarah Huckabee Sanders', 'Republican', 2027],
  ['CA', 'Gavin Newsom', 'Democrat', 2027],
  ['CO', 'Jared Polis', 'Democrat', 2027],
  ['CT', 'Ned Lamont', 'Democrat', 2027],
  ['DE', 'Matt Meyer', 'Democrat', 2029],
  ['FL', 'Ron DeSantis', 'Republican', 2027],
  ['GA', 'Brian Kemp', 'Republican', 2027],
  ['HI', 'Josh Green', 'Democrat', 2026],
  ['ID', 'Brad Little', 'Republican', 2027],
  ['IL', 'JB Pritzker', 'Democrat', 2027],
  ['IN', 'Mike Braun', 'Republican', 2029],
  ['IA', 'Kim Reynolds', 'Republican', 2027],
  ['KS', 'Laura Kelly', 'Democrat', 2027],
  ['KY', 'Andy Beshear', 'Democrat', 2027],
  ['LA', 'Jeff Landry', 'Republican', 2028],
  ['ME', 'Janet Mills', 'Democrat', 2027],
  ['MD', 'Wes Moore', 'Democrat', 2027],
  ['MA', 'Maura Healey', 'Democrat', 2027],
  ['MI', 'Gretchen Whitmer', 'Democrat', 2027],
  ['MN', 'Tim Walz', 'Democrat', 2027],
  ['MS', 'Tate Reeves', 'Republican', 2028],
  ['MO', 'Mike Kehoe', 'Republican', 2029],
  ['MT', 'Greg Gianforte', 'Republican', 2025],
  ['NE', 'Jim Pillen', 'Republican', 2027],
  ['NV', 'Joe Lombardo', 'Republican', 2027],
  ['NH', 'Kelly Ayotte', 'Republican', 2027],
  ['NJ', 'Phil Murphy', 'Democrat', 2026],
  ['NM', 'Michelle Lujan Grisham', 'Democrat', 2027],
  ['NY', 'Kathy Hochul', 'Democrat', 2027],
  ['NC', 'Josh Stein', 'Democrat', 2029],
  ['ND', 'Kelly Armstrong', 'Republican', 2028],
  ['OH', 'Mike DeWine', 'Republican', 2027],
  ['OK', 'Kevin Stitt', 'Republican', 2027],
  ['OR', 'Tina Kotek', 'Democrat', 2027],
  ['PA', 'Josh Shapiro', 'Democrat', 2027],
  ['RI', 'Dan McKee', 'Democrat', 2027],
  ['SC', 'Henry McMaster', 'Republican', 2027],
  ['SD', 'Larry Rhoden', 'Republican', 2027],
  ['TN', 'Bill Lee', 'Republican', 2027],
  ['TX', 'Greg Abbott', 'Republican', 2027],
  ['UT', 'Spencer Cox', 'Republican', 2029],
  ['VT', 'Phil Scott', 'Republican', 2027],
  ['VA', 'Glenn Youngkin', 'Republican', 2026],
  ['WA', 'Bob Ferguson', 'Democrat', 2029],
  ['WV', 'Patrick Morrisey', 'Republican', 2029],
  ['WI', 'Tony Evers', 'Democrat', 2027],
  ['WY', 'Mark Gordon', 'Republican', 2027],
];
