/**
 * US state metadata including house district counts (post-2020 Census).
 * Format: { abbr, name, houseDistricts, senateClass2Year, senateClass3Year }
 * Senate classes: Class 1 = 2024, Class 2 = 2026, Class 3 = 2028
 */

module.exports = [
  { abbr: 'AL', name: 'Alabama', districts: 7 },
  { abbr: 'AK', name: 'Alaska', districts: 1 },
  { abbr: 'AZ', name: 'Arizona', districts: 9 },
  { abbr: 'AR', name: 'Arkansas', districts: 4 },
  { abbr: 'CA', name: 'California', districts: 52 },
  { abbr: 'CO', name: 'Colorado', districts: 8 },
  { abbr: 'CT', name: 'Connecticut', districts: 5 },
  { abbr: 'DE', name: 'Delaware', districts: 1 },
  { abbr: 'FL', name: 'Florida', districts: 28 },
  { abbr: 'GA', name: 'Georgia', districts: 14 },
  { abbr: 'HI', name: 'Hawaii', districts: 2 },
  { abbr: 'ID', name: 'Idaho', districts: 2 },
  { abbr: 'IL', name: 'Illinois', districts: 17 },
  { abbr: 'IN', name: 'Indiana', districts: 9 },
  { abbr: 'IA', name: 'Iowa', districts: 4 },
  { abbr: 'KS', name: 'Kansas', districts: 4 },
  { abbr: 'KY', name: 'Kentucky', districts: 6 },
  { abbr: 'LA', name: 'Louisiana', districts: 6 },
  { abbr: 'ME', name: 'Maine', districts: 2 },
  { abbr: 'MD', name: 'Maryland', districts: 8 },
  { abbr: 'MA', name: 'Massachusetts', districts: 9 },
  { abbr: 'MI', name: 'Michigan', districts: 13 },
  { abbr: 'MN', name: 'Minnesota', districts: 8 },
  { abbr: 'MS', name: 'Mississippi', districts: 4 },
  { abbr: 'MO', name: 'Missouri', districts: 8 },
  { abbr: 'MT', name: 'Montana', districts: 2 },
  { abbr: 'NE', name: 'Nebraska', districts: 3 },
  { abbr: 'NV', name: 'Nevada', districts: 4 },
  { abbr: 'NH', name: 'New Hampshire', districts: 2 },
  { abbr: 'NJ', name: 'New Jersey', districts: 12 },
  { abbr: 'NM', name: 'New Mexico', districts: 3 },
  { abbr: 'NY', name: 'New York', districts: 26 },
  { abbr: 'NC', name: 'North Carolina', districts: 14 },
  { abbr: 'ND', name: 'North Dakota', districts: 1 },
  { abbr: 'OH', name: 'Ohio', districts: 15 },
  { abbr: 'OK', name: 'Oklahoma', districts: 5 },
  { abbr: 'OR', name: 'Oregon', districts: 6 },
  { abbr: 'PA', name: 'Pennsylvania', districts: 17 },
  { abbr: 'RI', name: 'Rhode Island', districts: 2 },
  { abbr: 'SC', name: 'South Carolina', districts: 7 },
  { abbr: 'SD', name: 'South Dakota', districts: 1 },
  { abbr: 'TN', name: 'Tennessee', districts: 9 },
  { abbr: 'TX', name: 'Texas', districts: 38 },
  { abbr: 'UT', name: 'Utah', districts: 4 },
  { abbr: 'VT', name: 'Vermont', districts: 1 },
  { abbr: 'VA', name: 'Virginia', districts: 11 },
  { abbr: 'WA', name: 'Washington', districts: 10 },
  { abbr: 'WV', name: 'West Virginia', districts: 2 },
  { abbr: 'WI', name: 'Wisconsin', districts: 8 },
  { abbr: 'WY', name: 'Wyoming', districts: 1 },
];
